service: gpt-snowflake-service  # Change this if you want a different service name

provider:
  name: aws
  runtime: python3.13  # Ensure this matches your Python version
  region: us-east-1  # Change to your preferred AWS region
  memorySize: 256
  timeout: 10

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app  # Adjust if your app is named differently
  pythonRequirements:
    dockerizePip: true

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

package:
  exclude:
    - node_modules/**
    - venv/**

